version: "3.8"

services:

  space_mongo:
    image: mongo
    container_name: space_mongo
    ports:
      - 27017:27017
    volumes:
      - mongospacedbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: space_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongospacedbdata:
  mongosensordbdata:
  rabbitmqdata:
